### ISSUE TITLE
new json rest API endpoint

### ISSUE THREAD

**Issue by funkenstrahlen** [xenim/django-radioportal#18]
**API calls I currently use**

* `getPodcastData(podcast_id) -> Podcast` returns all data for a podcast show
* `getNextLiveEvents(podcast_id, count) -> Event(s)` returns the *count* next planned liveevents of a specific podcast
* `getCalendar(start_date, end_date, count) -> Event(s)` returns a list of planned events. All parameters optional. `start_date`  today by default. `end_date` is nil by default. `count` is maybe 50 by default.
* `getAllPodcasts() -> Podcast(s)` returns all currently registered podcast shows.

Of course this is only a pseudo representation of the API calls. But I think you get the idea.

**Data Model**

Of course in json everything is a string. So handle NSURL as string too. The `?` at the end marks the optional parameters. That means the app can work if they are empty but of course it will not look that nice and have all the functions for those shows.

**Podcast**
* `podcast_id`: String (database id to refer this podcast)
* `feed_url`: NSURL?
* `artwork_url`: NSURL? (link to the original full size artwork image in the feed)
* `artwork_thumb_url`: NSURL? (thumb provided by xenim)
* `name`: String
* `subtitle`: String
* `description`: String
* `website_url`: NSURL?
* `email`: String?

more stuff that might not be in the rss feed. Maybe ask the podcasters to add them manually

* `irc_url`: NSURL?
* `webchat_url`: NSURL?
* `twitter_handle`: String?
* `flattr_handle`: String?

**Event**

* `duration`: Int? // in minutes
* `start_date` = String
* `event_title`: String
* `event_description`: String?
* `podcast_id`: String (database id to fetch more infos with another call)
* `stream_urls`: Array<String>
    * `mp3`: String
    * `hls`: String?
* `listeners`: Int?

**Comment by funkenstrahlen** [comment]
Just some other thoughts:

How do we handle podcast shows which are scheduled in the calendar to start streaming at a specific time and they don't because they are late. Or they forgot to remove the calendar entry.

I think this can be addressed like this:

* show is still listed in calendar feed (as long as the podcast creators do not update their calendar and remove the event)
* the app displays it in "upcoming today" section with the scheduled start time. Even if the start time already passed.
* **actually** live shows get fetched by a different api call. `getLiveEvents() -> Event(s)`. They will then be shown as live in the app with a play button to listen.

**Comment by cato-** [comment]
Current implementation will update the planned episode if the iCal entry. Planned episode which had not started within a day after the planned begin are removed automatically.

**Comment by cato-** [comment]
Regarding the data model: 
* What sizes are required for `artwork_thumb_url`? Currently only 150x150 is generated for the website, this might change in future versions, but additional resolutions might be provided without much additional affort
* `webchat_url` will propably not part of the API as it can be deducted easily from `irc_url`
* `flattr_handle` is currently not in xenim. I would like to include it as it is also available via the podcast-feed, but in a more generic form to include things like paypal.me as well.

**Comment by funkenstrahlen** [comment]
> What sizes are required for artwork_thumb_url? Currently only 150x150 is generated for the website, this might change in future versions, but additional resolutions might be provided without much additional affort

Currently I use about 60x60 images in the app. With @2x devices this requires 120x120, so 150x150 is enough for now. However for an iPad Version I will need @3x, so it is a good idea to build an API that is easily extensible for different sizes. I also use really large images in the player which are very large, so I use the imageurl that refers to the source image at the podcasts website.

Maybe we should have something like

```
artwork_thumbs: {
  original: "",
  150: "",
  300: ""
 ....
}
```

> webchat_url will propably not part of the API as it can be deducted easily from irc_url

I do not think so. There might be podcasts in the future that use a different chat service, so irc can be empty and webchat url can be set.

> flattr_handle is currently not in xenim. I would like to include it as it is also available via the podcast-feed, but in a more generic form to include things like paypal.me as well.

That makes sense. Maybe something like

```
donation: {
  flattr_id: ""
  paypal_id: ""
 ....
}
```

**Comment by funkenstrahlen** [comment]
> Planned episode which had not started within a day after the planned begin are removed automatically.

What do mean with removed? Maybe I do not have understand the xenim process yet. Are there two ways to schedule an event?

This is how I think it currently works (please correct me if wrong):

* user has .ical configured in his account
* adds an event in his calender
* xenim fetches .ical and updates its database of events
* I fetch the list of events with an API call saying: "give me everything that happens today and in the future."

**Comment by cato-** [comment]
I drew an image which hopefully explains everything (The numbers in brackets can be ignored, they are needed for graph generation only):

![image](https://cloud.githubusercontent.com/assets/429529/11995138/ae1db182-aa4b-11e5-910c-9b491f5f949e.png)
